name: Code Quality

on:
  push:
    branches: [ "main", "refactor-cpp-soft-posits" ]
  pull_request:
    branches: [ "main", "refactor-cpp-soft-posits" ]
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-14

    - name: Run clang-format-check
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '14'
        check-path: 'src include tests examples' 